class NumberOutOfRangeException(Exception):

    pass


class MalformedIntegerReceived(Exception):

    pass
